/**
 * generated by Xtext 2.36.0
 */
package gameofLife.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Cell Coord</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link gameofLife.myDsl.CellCoord#getX <em>X</em>}</li>
 *   <li>{@link gameofLife.myDsl.CellCoord#getY <em>Y</em>}</li>
 * </ul>
 *
 * @see gameofLife.myDsl.MyDslPackage#getCellCoord()
 * @model
 * @generated
 */
public interface CellCoord extends EObject
{
  /**
   * Returns the value of the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>X</em>' attribute.
   * @see #setX(int)
   * @see gameofLife.myDsl.MyDslPackage#getCellCoord_X()
   * @model
   * @generated
   */
  int getX();

  /**
   * Sets the value of the '{@link gameofLife.myDsl.CellCoord#getX <em>X</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>X</em>' attribute.
   * @see #getX()
   * @generated
   */
  void setX(int value);

  /**
   * Returns the value of the '<em><b>Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Y</em>' attribute.
   * @see #setY(int)
   * @see gameofLife.myDsl.MyDslPackage#getCellCoord_Y()
   * @model
   * @generated
   */
  int getY();

  /**
   * Sets the value of the '{@link gameofLife.myDsl.CellCoord#getY <em>Y</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Y</em>' attribute.
   * @see #getY()
   * @generated
   */
  void setY(int value);

} // CellCoord
