/**
 * generated by Xtext 2.36.0
 */
package gameofLife.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Dead To Alive Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see gameofLife.myDsl.MyDslPackage#getDeadToAliveRule()
 * @model
 * @generated
 */
public interface DeadToAliveRule extends ruleDefinition
{
} // DeadToAliveRule
