/**
 * generated by Xtext 2.36.0
 */
package gameofLife.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link gameofLife.myDsl.Model#getGrid <em>Grid</em>}</li>
 *   <li>{@link gameofLife.myDsl.Model#getRules <em>Rules</em>}</li>
 *   <li>{@link gameofLife.myDsl.Model#getSteps <em>Steps</em>}</li>
 * </ul>
 *
 * @see gameofLife.myDsl.MyDslPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Grid</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Grid</em>' containment reference.
   * @see #setGrid(gridDefinition)
   * @see gameofLife.myDsl.MyDslPackage#getModel_Grid()
   * @model containment="true"
   * @generated
   */
  gridDefinition getGrid();

  /**
   * Sets the value of the '{@link gameofLife.myDsl.Model#getGrid <em>Grid</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Grid</em>' containment reference.
   * @see #getGrid()
   * @generated
   */
  void setGrid(gridDefinition value);

  /**
   * Returns the value of the '<em><b>Rules</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rules</em>' containment reference.
   * @see #setRules(rulesDefinition)
   * @see gameofLife.myDsl.MyDslPackage#getModel_Rules()
   * @model containment="true"
   * @generated
   */
  rulesDefinition getRules();

  /**
   * Sets the value of the '{@link gameofLife.myDsl.Model#getRules <em>Rules</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rules</em>' containment reference.
   * @see #getRules()
   * @generated
   */
  void setRules(rulesDefinition value);

  /**
   * Returns the value of the '<em><b>Steps</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Steps</em>' containment reference.
   * @see #setSteps(stepsDefinition)
   * @see gameofLife.myDsl.MyDslPackage#getModel_Steps()
   * @model containment="true"
   * @generated
   */
  stepsDefinition getSteps();

  /**
   * Sets the value of the '{@link gameofLife.myDsl.Model#getSteps <em>Steps</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Steps</em>' containment reference.
   * @see #getSteps()
   * @generated
   */
  void setSteps(stepsDefinition value);

} // Model
