/**
 * generated by Xtext 2.36.0
 */
package gameofLife.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Neighbor</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link gameofLife.myDsl.Neighbor#getDx <em>Dx</em>}</li>
 *   <li>{@link gameofLife.myDsl.Neighbor#getDy <em>Dy</em>}</li>
 * </ul>
 *
 * @see gameofLife.myDsl.MyDslPackage#getNeighbor()
 * @model
 * @generated
 */
public interface Neighbor extends EObject
{
  /**
   * Returns the value of the '<em><b>Dx</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dx</em>' attribute.
   * @see #setDx(int)
   * @see gameofLife.myDsl.MyDslPackage#getNeighbor_Dx()
   * @model
   * @generated
   */
  int getDx();

  /**
   * Sets the value of the '{@link gameofLife.myDsl.Neighbor#getDx <em>Dx</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dx</em>' attribute.
   * @see #getDx()
   * @generated
   */
  void setDx(int value);

  /**
   * Returns the value of the '<em><b>Dy</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dy</em>' attribute.
   * @see #setDy(int)
   * @see gameofLife.myDsl.MyDslPackage#getNeighbor_Dy()
   * @model
   * @generated
   */
  int getDy();

  /**
   * Sets the value of the '{@link gameofLife.myDsl.Neighbor#getDy <em>Dy</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dy</em>' attribute.
   * @see #getDy()
   * @generated
   */
  void setDy(int value);

} // Neighbor
