/**
 * generated by Xtext 2.36.0
 */
package gameofLife.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>rules Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link gameofLife.myDsl.rulesDefinition#getRules <em>Rules</em>}</li>
 * </ul>
 *
 * @see gameofLife.myDsl.MyDslPackage#getrulesDefinition()
 * @model
 * @generated
 */
public interface rulesDefinition extends EObject
{
  /**
   * Returns the value of the '<em><b>Rules</b></em>' containment reference list.
   * The list contents are of type {@link gameofLife.myDsl.ruleDefinition}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rules</em>' containment reference list.
   * @see gameofLife.myDsl.MyDslPackage#getrulesDefinition_Rules()
   * @model containment="true"
   * @generated
   */
  EList<ruleDefinition> getRules();

} // rulesDefinition
