/**
 * generated by Xtext 2.36.0
 */
package gameofLife.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>steps Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link gameofLife.myDsl.stepsDefinition#getCount <em>Count</em>}</li>
 * </ul>
 *
 * @see gameofLife.myDsl.MyDslPackage#getstepsDefinition()
 * @model
 * @generated
 */
public interface stepsDefinition extends EObject
{
  /**
   * Returns the value of the '<em><b>Count</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Count</em>' attribute.
   * @see #setCount(int)
   * @see gameofLife.myDsl.MyDslPackage#getstepsDefinition_Count()
   * @model
   * @generated
   */
  int getCount();

  /**
   * Sets the value of the '{@link gameofLife.myDsl.stepsDefinition#getCount <em>Count</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Count</em>' attribute.
   * @see #getCount()
   * @generated
   */
  void setCount(int value);

} // stepsDefinition
