/**
 * generated by Xtext 2.36.0
 */
package gameofLife.myDsl.impl;

import gameofLife.myDsl.DeadToAliveRule;
import gameofLife.myDsl.MyDslPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Dead To Alive Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class DeadToAliveRuleImpl extends ruleDefinitionImpl implements DeadToAliveRule
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DeadToAliveRuleImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.DEAD_TO_ALIVE_RULE;
  }

} //DeadToAliveRuleImpl
